platform :ios, '10.0'

target 'Spalanie' do
  use_frameworks!

  # Pods for Spalanie
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  
  target 'SpalanieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpalanieUITests' do
    # Pods for testing
  end

end
